Layout/ExtraSpacing:
  Enabled: false

Style/IfInsideElse:
  Enabled: false
Style/GuardClause:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  Max: 15

Style/IfUnlessModifier:
  Enabled: false
