source 'https://rubygems.org'

gemspec name: 'property', path: '.'
# gem 'faker'
# gem 'lookbook', '~> 2.3'
# gem 'pagy', '~> 9.4'

group :development, :test do
  gem 'faker'
end

group :development do
  gem 'yard'
end

group :test do
  gem 'rspec'
end
